[workspace]
resolver = "2"
members = ["apps/cli", "apps/api"]
default-members = ["apps/cli"]

[workspace.package]
edition = "2021"
rust-version = "1.75"
license = "MIT"
authors = ["Duyet Le <me@duyet.net>"]
repository = "https://github.com/duyet/summa"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3
